### ISSUE TITLE
Avoid file transfers in hpc load balancer

### ISSUE THREAD

**Issue by linusseelinger** [UM-Bridge/umbridge#26] opened 2023-11-07 08:47 UTC
The hpc load balancer currently transfers files to find out the address of a specific task's model instance.

Task: Avoid file transfers. Maybe need to chat with hyperqueue devs about how to make this possible.

**Comment by Schlevidon** [comment] 2024-03-05 17:02
Duplicate of #62.

**Closed** 2024-03-05 17:02 UTC
